# Для отказоустойчивости и одновременно минимального потребления создадим абстракцию HPA. Знал о ней заранее из статьи на хабре, немного погугли и почитал как работает.
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: app-hpa
spec:
  scaleTargetRef: # Таргетом наш деплоймент
    apiVersion: apps/v1
    kind: Deployment
    name: app-deployment
  minReplicas: 2 # минимальное количество 2 для соблюдения отказоустойчивости
  maxReplicas: 4 # максимальное количество 4 при пиковых нагрузках
  metrics: # Выбираем метрику. Знаю, что можно сделать кастомную под конкретное приложение
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 85 # ставим процентную нагрузку