# создаём роль для наших job, которые будут патчить HPA
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: cron-runner
rules:
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["patch", "get"]

---
# Биндим роль с сервис аккаунтом
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cron-runner
  namespace: default
subjects:
- kind: ServiceAccount
  name: sa-cron-runner
  namespace: default
roleRef:
  kind: Role
  name: cron-runner
  apiGroup: rbac.authorization.k8s.io

---
# Создаём сам сервис аккаунт
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-cron-runner
  namespace: default

